export const timerPreviousValue = 'TIMER_PREVIOUS_VALUE'
export const timerPlayAlert = 'TIMER_PLAY_ALERT'
export const userAlarmFile = 'USER_ALARM_FILE'
export const userAlarmVolume = 'USER_ALARM_VOLUME'
export const userAlwaysOnTop = 'USER_ALWAYS_ON_TOP'